import Image from "next/image";
import Link from "next/link";
import { site } from "@/lib/site";
import { Container } from "@/components/ui/Container";

const year = new Date().getFullYear();

export function Footer() {
  return (
    <footer className="bg-slate-950 text-slate-300">
      <Container className="py-14 lg:py-16">
        <div className="grid gap-12 lg:grid-cols-12">
          <div className="lg:col-span-5">
            <Image
              src="/images/brand/logo.svg"
              alt={site.name}
              width={2127}
              height={405}
              unoptimized
              className="h-10 w-auto grayscale brightness-[2.2]"
            />
            <p className="mt-6 max-w-md text-sm leading-7 text-slate-400">
              Flights above 30,000 feet have been made in the atmospheric waves generated by
              Mount Washington and the surrounding peaks. Every October, pilots gather at Gorham
              to fly them.
            </p>
            <a
              href={`mailto:${site.email}`}
              className="mt-6 inline-flex items-center gap-2 rounded-full bg-white/10 px-5 py-2.5 text-sm font-semibold text-white ring-1 ring-white/20 transition-colors hover:bg-white/20"
            >
              {site.email}
            </a>
          </div>

          <div className="lg:col-span-3">
            <p className="font-display text-xs font-semibold uppercase tracking-[0.28em] text-sky-400">
              Explore
            </p>
            <ul className="mt-5 grid gap-2.5 text-sm">
              {site.nav.map((item) => (
                <li key={item.href}>
                  <Link href={item.href} className="text-slate-400 transition-colors hover:text-white">
                    {item.label}
                  </Link>
                </li>
              ))}
              <li>
                <Link href="/contact" className="text-slate-400 transition-colors hover:text-white">
                  Contact
                </Link>
              </li>
            </ul>

            <p className="mt-8 font-display text-xs font-semibold uppercase tracking-[0.28em] text-sky-400">
              Search
            </p>
            <form action="/search" method="get" role="search" className="mt-4">
              <label htmlFor="footer-search" className="sr-only">
                Search the site
              </label>
              <div className="relative">
                <input
                  id="footer-search"
                  type="search"
                  name="q"
                  placeholder="Search the site…"
                  autoComplete="off"
                  spellCheck={false}
                  className="w-full rounded-full border border-white/15 bg-white/5 py-2.5 pl-4 pr-11 text-sm text-white outline-none transition placeholder:text-slate-500 focus:border-sky-400/60 focus:bg-white/10 focus:ring-2 focus:ring-sky-400/20"
                />
                <button
                  type="submit"
                  aria-label="Search"
                  className="absolute right-1.5 top-1/2 grid size-8 -translate-y-1/2 place-items-center rounded-full text-slate-400 transition-colors hover:bg-white/10 hover:text-white"
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="size-4" aria-hidden="true">
                    <circle cx="11" cy="11" r="6.5" />
                    <path d="m16.5 16.5 4 4" strokeLinecap="round" />
                  </svg>
                </button>
              </div>
            </form>
          </div>

          <div className="lg:col-span-4">
            <p className="font-display text-xs font-semibold uppercase tracking-[0.28em] text-sky-400">
              Wave camp
            </p>
            <ul className="mt-5 grid gap-3 text-sm text-slate-400">
              <li>
                Every October, from Columbus Day weekend through the following weekend.
              </li>
              <li>{site.location.airport}</li>
              <li>{site.location.town}</li>
              <li>
                <Link
                  href="/flying"
                  className="font-medium text-sky-300 transition-colors hover:text-sky-200"
                >
                  Required reading before you fly →
                </Link>
              </li>
              <li className="pt-1 text-xs leading-6 text-slate-500">
                Camp information and signup sheets go out on the email list each season — write
                to{" "}
                <a href={`mailto:${site.email}`} className="text-slate-400 underline underline-offset-4 hover:text-white">
                  {site.email}
                </a>
                .
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-14 flex flex-col gap-3 border-t border-white/10 pt-6 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between">
          <p>
            © {year} {site.name}. All rights reserved.
          </p>
          <p>
            Website sponsored by{" "}
            <a
              href={site.sponsor.url}
              className="font-medium text-slate-400 transition-colors hover:text-white"
            >
              {site.sponsor.name}
            </a>
          </p>
        </div>
      </Container>
    </footer>
  );
}
